#!/usr/bin/env php
<?php

require __DIR__ . '/../src/bootstrap.php';

use Polargraph\Console\Application;
use Polargraph\Di;

if (PHP_SAPI !== 'cli') {
    echo 'Warning: Polargraph should be invoked via the CLI version of PHP, not the ' . PHP_SAPI . ' SAPI' . PHP_EOL;
}

if(function_exists('ini_set')) {
    @ini_set('display_errors', 1);
    @ini_set('memory_limit', '512M');
}

try {
    $di = new Di();
    $console = new Application($di);
    $console->run();
} catch (Exception $exception) {
    echo $exception->getMessage(), PHP_EOL;
    echo $exception->getTraceAsString(), PHP_EOL;
}
